### ISSUE TITLE
Negative daily cases for Spain

### ISSUE THREAD

**Issue by daviddoji** [fangohr/coronavirus-2020#44]
It must be an error in the data (negative new cases), but it doesn't make too much sense to have negative numbers in daily change plots.
Spotted in the plot for Spain (attached screenshot)

![imagen](https://user-images.githubusercontent.com/4411314/82372904-14af8e00-9a1d-11ea-948e-5fbc3b5581c8.png)

A tests for this issue could be useful.

**Comment by fangohr** [comment]
Thanks for the observation.

I would assume that the problem is with the data we get from Johns Hopkins: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Checking in the table at the bottom of https://oscovida.github.io/html/Spain.html, we see that this happens when the total number of cases changes from 213024 on 23 April to 202990 on 24 April. 

So this  does come from the data; and hopefully corrects for errors below.

I could imagine two things to do:

(i) check the issues for the Johns Hopkins University data and/or report the problem there (https://github.com/CSSEGISandData/COVID-19/issues). 

(ii) use data from the European data centre (Thomas M has some code to read it) as an alternative to Johns Hopkins.

I'd hesitate to check the data and exclude negative values - sometimes the way a country reports data has changed, and it is not clear if hiding that is always the right thing to do.

**Comment by daviddoji** [comment]
There was already an issue fired for the JHU data. It's what we've discussed about the way started to count cases at a certain point (PCR+ only from April 24th whereas PCR+ and Ab+ before that date).

Perhaps it's a good idea to have other sources for comparison. I'll check Thomas M code.

**Comment by fangohr** [comment]
@daviddoji - I have put a fix in (04c3d64). Please check the data tomorrow at some point, and close the issue if you are happy with it.

**Comment by daviddoji** [comment]
The fix doesn't  fix the problem although the approach looks good to me. I still can see the same issue when executing from https://hub.gke.mybinder.org/user/oscovida-oscovida.github.io-2qzv0hfq/notebooks/ipynb/Spain.ipynb
![imagen](https://user-images.githubusercontent.com/4411314/82746887-df949a00-9d94-11ea-9aa1-7de2d5a91642.png)

**Comment by fangohr** [comment]
You were too fast :). Can you check again?

**Comment by daviddoji** [comment]
Now it looks much better :D
